version: '3.9'

services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    env_file: .env
    depends_on:
    - db:
        condition: service_healthy

  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    env_file: .env
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5